---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 20.3.1

inputs:
  - name: dp-design-system

outputs:
  - name: build

run:
  path: dp-design-system/ci/scripts/build.sh
