---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: onsdigital/dp-concourse-tools-node-go
    tag: latest

inputs:
  - name: dp-design-system

outputs:
  - name: build

run:
  path: dp-design-system/ci/scripts/build.sh
